DROP TABLE IF EXISTS stop;
DROP TABLE IF EXISTS line;
DROP TABLE IF EXISTS lineSegment;
DROP TABLE IF EXISTS stop_line;
DROP TABLE IF EXISTS bus;
DROP TABLE IF EXISTS busSegment;

CREATE TABLE stop(
	sid INTEGER PRIMARY KEY,
	sname VARCHAR(50) NOT NULL
);

CREATE TABLE line(
	lid INTEGER PRIMARY KEY,
	lname VARCHAR(50) NOT NULL,
	segmentCount INTEGER,
	firstStop INTEGER REFERENCES stop(sid) ON DELETE RESTRICT ON UPDATE CASCADE DEFERRABLE INITIALLY IMMEDIATE,
	CHECK (segmentCount > 0)
);

CREATE TABLE lineSegment(
	lsid INTEGER PRIMARY KEY,
	lid REFERENCES line(lid) ON DELETE RESTRICT ON UPDATE CASCADE DEFERRABLE INITIALLY IMMEDIATE,
	timeDiff INTEGER,
	nextStop INTEGER REFERENCES stop(sid) ON DELETE RESTRICT ON UPDATE CASCADE DEFERRABLE INITIALLY IMMEDIATE,
	CHECK (timeDiff > 0)
);

CREATE TABLE stop_line(
	sid INTEGER REFERENCES stop(sid) ON DELETE RESTRICT ON UPDATE CASCADE DEFERRABLE INITIALLY IMMEDIATE,
	lid INTEGER REFERENCES stop(sid) ON DELETE RESTRICT ON UPDATE CASCADE DEFERRABLE INITIALLY IMMEDIATE
);

CREATE TABLE bus(
	bid INTEGER PRIMARY KEY,
	lid REFERENCES line(lid) ON DELETE RESTRICT ON UPDATE CASCADE DEFERRABLE INITIALLY IMMEDIATE,
	startTime INTEGER,
	capacity INTEGER,
	CHECK (startTime > 0 AND capacity > 0)
);

CREATE TABLE busSegment(
	lsid INTEGER REFERENCES lineSegment(lsid) ON DELETE RESTRICT ON UPDATE CASCADE DEFERRABLE INITIALLY IMMEDIATE,
	bid INTEGER REFERENCES bus(bid) ON DELETE RESTRICT ON UPDATE CASCADE DEFERRABLE INITIALLY IMMEDIATE,
	passengers INTEGER,
	CHECK (passengers > 0)
);

INSERT INTO stop(sid, sname) VALUES (1, "STOP A");
INSERT INTO line(lid, lname, segmentCount, firstStop) VALUES (1, "L1", 1, 1);
INSERT INTO stop_line(sid, lid) VALUES (1, 1);
